---
title: "Multinomial Model BRMS (Abandoned)"
author: "Vichearith"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Read data
# Load packages
library(here)
library(dplyr)
library(readr)
library(rstan)
library(bayesrules)
library(tidyverse)
library(bayesplot)
library(rstanarm)
library(janitor)
library(tidybayes)
library(broom.mixed)
library(sf)
library(tidycensus)
library(openxlsx)
library(s2)
library(nycgeo)
library(CARBayes)
library(spData) 
library(spdep)


# themes
theme_set(theme_minimal())

```

```{r}
# Load data

#  Read CSV File
csv_file_clean <- read_csv("clean_data/nyc_names_vichy_complied.csv")
#  Read Shape File
shape_file_clean <- st_read("clean_data/nyc_data_vichy_complied.shp", crs = 4269)
#  Replace Column abbr Names in Shape File with full name from CSV
colnames(shape_file_clean) <- colnames(csv_file_clean)

# Verify
names(shape_file_clean)
names(csv_file_clean)
dim(csv_file_clean)

csv_file_clean %>%  
  filter(transportation_desert_4cat== 'Poor') %>% 
  group_by(nta_type)


# csv_file_clean <- csv_file_clean %>% 
#   na.omit( mean_income) %>%
#   na.omit( mean_rent) %>%
#   na.omit( unemployment_count) %>%
#   na.omit( school_count) %>%
#   na.omit( store_count) %>%
#   na.omit( bus_count) %>%
#   na.omit( eviction_count) %>%
#   na.omit( uninsured_count) %>%
#   na.omit( white_count) %>%
#   na.omit( latinx_count) %>%
#   na.omit( asian_count)
csv_file_clean_2 <- csv_file_clean %>%  mutate(nonwhite = latinx_count + asian_count + native_count + black_count )
csv_file_clean_2 %>%  summarise(unique(transportation_desert_4cat))
```



# BRMS Multinomial 

## Transportation Desert ~ 
```{r}
library(brms) 

```


```{r eval=FALSE}
# trans_desert_multinomial_model_1 <- brm(transportation_desert_4cat ~ 1 +
#               mean_income +
#               mean_rent +
#               unemployment_count +
#               school_count +
#               store_count +
#               bus_count +
#               eviction_count +
#               uninsured_count +
#               white_count+
#               black_count+
#               latinx_count +
#               asian_count +
#               (1|borough) ,
#             data = csv_file_clean,
#             family= categorical(link = "logit"),
#             chains = 4,
#             iter = 2000*2)
# saveRDS(trans_desert_multinomial_model_1, "trans_desert_multinomial_model_1.rds")
# 
# trans_desert_multinomial_model_2 <- brm(transportation_desert_4cat ~ 1 +
#               mean_income +
#               mean_rent +
#               unemployment_count +
#               school_count +
#               store_count +
#               bus_count +
#               eviction_count +
#               uninsured_count +
#               white_count+
#               nonwhite +
#               (1|borough) ,
#             data = csv_file_clean_2,
#             family= categorical(link = "logit"),
#             chains = 4,
#             iter = 2000*2)
# saveRDS(trans_desert_multinomial_model_2, "trans_desert_multinomial_model_2.rds")
# 
# trans_desert_multinomial_model_3 <- brm(transportation_desert_4cat ~ 1 +
#               mean_ridership + 
#               bus_count +
#               (1|borough) ,
#             data = csv_file_clean_2,
#             family= categorical(link = "logit"),
#             chains = 4,
#             iter = 2000*2)
# saveRDS(trans_desert_multinomial_model_3, "trans_desert_multinomial_model_3.rds")
# trans_desert_multinomial_model_4 <- brm(transportation_desert_4cat ~ 1 +
#               school_count +
#               store_count +
#               bus_count +
#               (1|borough) ,
#             data = csv_file_clean_2,
#             family= categorical(link = "logit"),
#             chains = 4,
#             iter = 2000*2)
# saveRDS(trans_desert_multinomial_model_4, "trans_desert_multinomial_model_4.rds")
# trans_desert_multinomial_model_5 <- brm(transportation_desert_4cat ~ 1 +
#               school_count +
#               store_count +
#               bus_count +
#               (1|borough) ,
#             data = csv_file_clean_2,
#             family= categorical(link = "logit"),
#             chains = 4,
#             iter = 500*2)
# saveRDS(trans_desert_multinomial_model_5, "trans_desert_multinomial_model_5.rds")
```


```{r eval=FALSE}
trans_desert_multinomial_model_1 <- readRDS("trans_desert_multinomial_model_1.rds")
trans_desert_multinomial_model_2 <- readRDS("trans_desert_multinomial_model_2.rds")
trans_desert_multinomial_model_3 <- readRDS("trans_desert_multinomial_model_3.rds")
trans_desert_multinomial_model_4 <- readRDS("trans_desert_multinomial_model_4.rds")
trans_desert_multinomial_model_5 <- readRDS("trans_desert_multinomial_model_5.rds")
```


```{r eval=FALSE}
summary(trans_desert_multinomial_model_1)
summary(trans_desert_multinomial_model_2)
summary(trans_desert_multinomial_model_3)
summary(trans_desert_multinomial_model_4)
```

## Model 1 

```{r eval=FALSE}
plot(trans_desert_multinomial_model_1, ask = FALSE)
```


```{r eval=FALSE}
WAIC(trans_desert_multinomial_model_1)
```


```{r eval=FALSE}
pp_check(trans_desert_multinomial_model_1)
```

## Model 2 
```{r eval=FALSE}
plot(trans_desert_multinomial_model_2, ask = FALSE)
```


```{r eval=FALSE}
WAIC(trans_desert_multinomial_model_2)
```


```{r eval=FALSE}
pp_check(trans_desert_multinomial_model_2)
```


## Model 3 

```{r eval=FALSE}
plot(trans_desert_multinomial_model_3, ask = FALSE)
```


```{r eval=FALSE}
WAIC(trans_desert_multinomial_model_3)
```


```{r eval=FALSE}
pp_check(trans_desert_multinomial_model_3)
```

## Model 4 
```{r eval=FALSE}
plot(trans_desert_multinomial_model_4, ask = FALSE)
```


```{r eval=FALSE}
WAIC(trans_desert_multinomial_model_4)
```


```{r eval=FALSE}
pp_check(trans_desert_multinomial_model_4)
```

```{r}

csv_file_clean_2 %>%  summarise(unique(transportation_desert_4cat))
result <- csv_file_clean_2 %>% 
  dplyr::select(transportation_desert_4cat) %>% 
  mutate(pred = 
           predict(trans_desert_multinomial_model_4))

```

```{r}


names(csv_file_clean_2)
csv_file_clean_2 <- csv_file_clean_2 %>%  pivot_wider(
  names_from = transportation_desert_4cat,
  values_from = perc_covered_by_transit,
  values_fill = 0
)
csv_file_clean_2$trasportation_desert = with(csv_file_clean_2, cbind(Limited , Excellent, Satisfactory))
  
names(csv_file_clean_2)

trans_desert_multinomial_model_5 <- brm(bf(trasportation_desert) ~ 1 +
              school_count +
              store_count +
              bus_count +
              (1|borough) ,
            data = csv_file_clean_2,
            family=multinomial(),
            chains = 4,
            iter = 2000*2)
saveRDS(trans_desert_multinomial_model_5, "trans_desert_multinomial_model_5.rds")

```
