---
title: "NaiveBayes"
author: "Sam Ding"
date: "12/4/2021"
output: html_document
---
```{r}
library(e1071)
library(ggplot2)
library(tidyverse)
```

## Load Data
```{r}
nyc_clean <- read_csv("clean_data/nyc_names_vichy_complied2.csv")

nyc_clean2 <- nyc_clean %>%
  mutate(transportation_desert_4cat = factor(transportation_desert_4cat, levels=c("Poor", "Limited", "Satisfactory", "Excellent"))) %>%
  mutate(transportation_desert_4num = factor(as.numeric(transportation_desert_4cat))) %>%
   mutate(asian_perc = (asian_count / total_pop) * 100) %>%
   mutate(white_perc = (white_count / total_pop)* 100) %>%
   mutate(black_perc = (black_count / total_pop)* 100) %>%
   mutate(latinx_perc = (latinx_count / total_pop)* 100) %>%
   mutate(native_perc = (native_count / total_pop)* 100) %>%
   mutate(below_poverty_perc = (below_poverty_line_count / total_pop) * 100) %>%
   mutate(noncitizen_perc = (noncitizen_count / total_pop)* 100) %>%
   mutate(evictions_perc = (eviction_count / total_pop)* 100) %>%
   mutate(uninsured_perc = (uninsured_count / total_pop)* 100) %>%
  mutate(unemployment_perc = (unemployment_count / total_pop)* 100) %>%
  filter(nta_type == 0)

```
```{r}
ggplot(nyc_clean2, aes(x=asian_perc)) + geom_density()
```


## Train Models

```{r}
# Run the algorithm using only data on bill length
naive_model_1 <- naiveBayes(transportation_desert_4cat ~
                              mean_income +
                              mean_rent +
                              unemployment_perc +
                              evictions_perc +
                              noncitizen_perc +
                              below_poverty_perc +
                              native_perc +
                              latinx_perc +
                              white_perc +
                              asian_perc +
                              school_count +
                              store_count +
                              bus_count ,
                            data = nyc_clean2)

#  This model 2 has similar recipe as the Ordinal model
naive_model_2 <- naiveBayes(transportation_desert_4cat ~ 
                              mean_income +
                              below_poverty_perc +
                              eviction_count + 
                              store_count,
                            data =nyc_clean2)

saveRDS(naive_model_2, "naive_model_2.rds")

```

## Model Evaluation

### Cross-validation
```{r}
naive_classification_summary(naive_model_1, nyc_clean2, y="transportation_desert_4cat")
naive_classification_summary_cv(naive_model_1, nyc_clean2, y="transportation_desert_4cat", k=10)$cv
naive_classification_summary(naive_model_2, nyc_clean2, y="transportation_desert_4cat")
(naive2_prediction <- naive_classification_summary_cv(naive_model_2, nyc_clean2, y="transportation_desert_4cat", k=10)$cv)

```
```{r}
library(tidyverse)
prediction <- as.data.frame(naive2_prediction) %>%
  pivot_longer(
  cols= Poor:Excellent, 
  names_to = 'Predictions', 
  values_to = 'Probability'
) %>% 
  mutate(Probability = as.numeric(str_extract(Probability,'\\d+\\.\\d+'))/100)

prediction %>%  
  ggplot(aes(x=transportation_desert_4cat, y=Probability, fill=Predictions)) + 
  geom_bar(position="fill", stat="identity") 

```

The bar graph shows that the second model successfully predicts __Poor__ and __Excellent__ yet fails to categories __Limited__ and __Satisfactory__. This model only predicts the extreme cases as the top outcome. 


```{r}

#  Example of making prediciton withi new input. 
pred <- predict(naive_model_2, 
        newdata = data.frame( 
    mean_income= 100000, 
    evictions_perc = 2,
    below_poverty_perc = 2.1,
    school_count= 12, 
    store_count= 50)
    , type = "raw")

as.data.frame(pred)
```

