---
title: "Ordinal models"
author: "Sam Ding"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rstanarm)
library(rstan)
library(readr)
library(dplyr)
library(broom.mixed)
library(bayesrules)
library(rsample)
```

```{r}
nyc_clean <- read_csv("clean_data/nyc_names_vichy_complied2.csv")

nyc_clean2 <- nyc_clean %>%
  mutate(transportation_desert_4cat = factor(transportation_desert_4cat, levels=c("Poor", "Limited", "Satisfactory", "Excellent"))) %>%
  mutate(transportation_desert_4num = factor(as.numeric(transportation_desert_4cat))) %>%
   mutate(asian_perc = (asian_count / total_pop) * 100) %>%
   mutate(white_perc = (white_count / total_pop)* 100) %>%
   mutate(black_perc = (black_count / total_pop)* 100) %>%
   mutate(latinx_perc = (latinx_count / total_pop)* 100) %>%
   mutate(native_perc = (native_count / total_pop)* 100) %>%
   mutate(below_poverty_perc = (below_poverty_line_count / total_pop) * 100) %>%
   mutate(noncitizen_perc = (noncitizen_count / total_pop)* 100) %>%
   mutate(uninsured_perc = (uninsured_count / total_pop)* 100) %>%
  mutate(unemployment_perc = (unemployment_count / total_pop)* 100) %>%
  filter(nta_type == 0)

```


```{r}
data_split <- initial_split(nyc_clean2, prop = .8) 
data_train <- training(data_split)
data_test <- testing(data_split) 


quantile(nyc_clean2$perc_covered_by_transit)

```

```{r}
model1 <- stan_polr(transportation_desert_4num ~   mean_income + unemployment_perc + below_poverty_perc + eviction_count + uninsured_perc +white_perc + asian_perc + black_perc + latinx_perc + school_count + store_count, data =data_train, prior=R2(0.5),iter=500, seed = 86437, refresh=0, prior_PD=FALSE)
# saveRDS(model1, 'ordinal_model_1.rds')

model2 <- stan_polr(transportation_desert_4num ~ mean_income + below_poverty_perc + eviction_count + store_count, data =data_train, prior=R2(0.5),iter=500, seed = 86437, refresh=0, prior_PD=FALSE)
# saveRDS(model2, 'ordinal_model_2.rds')

model3 <- stan_polr(transportation_desert_4num~ store_count+ mean_rent+ mean_income+ below_poverty_perc, data =data_train, prior=NULL,iter=500, seed = 86437, refresh=0, prior_PD=FALSE)
```

## PP check and Tidy
```{r}
# summary(model1)

# pp_check(model1)
# pp_check(model2)
# pp_check(model3)

# tidy(model1, effects = "fixed", conf.int = TRUE, conf.level = 0.8)
# tidy(model2, effects = "fixed", conf.int = TRUE, conf.level = 0.8)
tidy(model3, effects = "fixed", conf.int = TRUE, conf.level = 0.8)

# summary_table <- coef(model2)
# 
# pval <- pnorm(abs(summary_table[, "t value"]),lower.tail = FALSE)* 2
# summary_table <- cbind(summary_table, "p value" = round(pval,3))
# summary_table
```

```{r}
ordinal_accuracy<-function(post_preds,mydata){
  post_preds<-as.data.frame(post_preds)
  results<-c()
  for (j in (1:length(post_preds))){
    results[j]<-as.numeric(tail(names(sort(table(post_preds[,j]))))[4])
    }
  results<-as.data.frame(results)
  compare<-cbind(results,mydata$transportation_desert_4num) %>%
    mutate(results=as.numeric(results)) %>%
    mutate(`mydata$transportation_desert_4num`=as.numeric(`mydata$transportation_desert_4num`))%>%
    mutate(accuracy=ifelse(as.numeric(results)==as.numeric(`mydata$transportation_desert_4num`),1,0))
  print(sum(compare$accuracy)/length(post_preds))
}
```

## MCMC Diagnostic
```{r}
mcmc_trace(model2)
mcmc_dens_overlay(model2)
```


```{r}
nyc_clean2[is.na(nyc_clean2)] = 0

set.seed(86437)
my_prediction1 <- posterior_predict(
  model1, 
  newdata = data_test)

my_prediction2 <- posterior_predict(
  model2, 
  newdata = data_test)

my_prediction3 <- posterior_predict(
  model3, 
  newdata = data_test)

nyc_clean2 %>%
  ggplot(aes(x=mean_income)) + geom_density()


set.seed(86437)
ordinal_accuracy(my_prediction1,data_test)
ordinal_accuracy(my_prediction2,data_test)
ordinal_accuracy(my_prediction3,data_test)

pred <- posterior_predict(
  model2, 
  newdata = data.frame( 
    # borough = "Manhattan",
    mean_income= 100000, 
    eviction_count = 20,
    below_poverty_perc = 2.1,
    # school_count= 12, 
    store_count= 50))
  df <- as.data.frame(pred) %>%
    mutate(Classification  = case_when(
    `1` == 1 ~ 'Poor',
    `1` == 2 ~ 'Limited',
    `1` == 3 ~ 'Satisfactory',
    `1` == 4 ~ 'Excellent' )) %>%
  dplyr::select(Classification)
    
    tab <- table(df) %>% sort(decreasing=TRUE)
    names(dimnames(tab)) <- c("Classification")
    tab
    
    
    
```

```{r, eval=false}
df <- as.data.frame(my_prediction2)


# first remember the names
n <- df_switched$name

# transpose all but the first column (name)
df_switched <- as.data.frame(t(df_switched))
colnames(df_switched) <- n

aggregated_df <- data.frame("test", "test")
names(aggregated_df) <- c("highestPred", "actual")
aggregated_df <- aggregated_df[-1,]

names(sort(-table(df[1])))[1]


for (i in 1:36) {
  highestPred <- names(sort(-table(df[i])))[1]
  actual <- data_test$transportation_desert_4num[i]
  newdf <- data.frame(highestPred, actual)
  names(newdf) <- c("highestPred", "actual")
  aggregated_df <- rbind(aggregated_df, newdf)
}

aggregated_df$value = 1

ggplot(aggregated_df, aes(x=actual, y=value, fill=highestPred)) + geom_bar(position="fill", stat="identity") 




```

```{r}
prediction_long <- my_prediction3 %>% 
  t() %>% 
  as.tibble() %>%
  mutate_if(is.character, as.numeric) %>%
  rownames_to_column() %>% 
  rowwise(id=rowname) %>%
  summarize(median=ifelse(mean(c_across(where(is.numeric)))>3.5, ceiling(mean(c_across(where(is.numeric)))), floor(mean(c_across(where(is.numeric)))))) %>%
  rename(predicted_desert = median)%>%
  mutate(predicted_desert = case_when(
    predicted_desert==1 ~ "Poor",
    predicted_desert ==2 ~ "Limited",
    predicted_desert ==3 ~ "Satisfactory",
    TRUE ~ "Excellent",
  ))  %>%
  mutate(predicted_desert = factor(predicted_desert, levels=c("Poor", "Limited", "Satisfactory", "Excellent")))

data_test %>%
  select(nta_id, borough, transportation_desert_4cat) %>%
  rownames_to_column() %>%
  left_join(., prediction_long, by="rowname") %>%
  
  ggplot(aes(x=transportation_desert_4cat, fill=predicted_desert)) + 
  geom_bar(position="fill")+
  scale_y_continuous(labels = seq(0, 100, by = 25)) +
  labs(title="Accessibility Predictions by Observed Category", y="Proportion", x="")+
    theme(panel.grid.major.x = element_line("transparent"),
         # axis.text.y.left = element_blank(),
          axis.text.x.bottom = element_text(size = 12, face = "bold"),
          plot.title = element_text(family="DIN Condensed", size =20, hjust=.5, face = "bold")) +
   scale_fill_manual(values=c("#895F32","#E9DBC2","#7D9B8A", "#395645"),
                       guide = guide_legend(title = "Subway Accessibility \nCategory"), na.value="#D6D6D6")
```


```{r}
ggplot(nyc_clean2, aes(x=perc_covered_by_traansit)) + geom_density()
```
