---
title: "vichy"
author: "Vichearith"
date: "11/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Read data
# Load packages
library(here)
library(dplyr)
library(readr)
library(rstan)
library(bayesrules)
library(tidyverse)
library(bayesplot)
library(rstanarm)
library(janitor)
library(tidybayes)
library(broom.mixed)
library(sf)
library(tidycensus)
library(openxlsx)
library(s2)
library(nycgeo)
library(CARBayes)
library(spData) 
library(spdep)


# themes
theme_set(theme_minimal())

```

```{r}
# Load data
vari_names <- read_csv(here("clean_data", "nyc_names.csv"))
nyc_clean <- st_read(here("clean_data", "nyc_data.shp"), crs = 4269, quiet=T) 
colnames(nyc_clean) <- colnames(vari_names)

```



```{r}
nyc_clean <- nyc_clean %>%
  mutate(transportation_desert_4cat = case_when(
    transportation_desert_4cat==1 ~ "Poor",
    transportation_desert_4cat ==2 ~ "Limited",
    transportation_desert_4cat ==3 ~ "Satisfactory",
     transportation_desert_4cat ==4 ~ "Excellent",
  ))  %>%
  mutate(transportation_desert_4cat = factor(transportation_desert_4cat, levels=c("Poor", "Limited", "Satisfactory", "Excellent")))

nyc_clean$transportation_desert_4cat <- relevel(nyc_clean$transportation_desert_4cat, ref = 'Poor')
names(nyc_clean)

nyc_clean %>%  as.tibble()

```

# BRMS Multinomial 
```{r}
library(brms)

N <- 15
dat <- data.frame(
    y1 = rbinom(N, 10, 0.3), y2 = rbinom(N, 10, 0.5), 
    y3 = rbinom(N, 10, 0.7), x = rnorm(N)
)
dat$size <- with(dat, y1 + y2 + y3)
dat$y <- with(dat, cbind(y1, y2, y3))

# prior <- prior(normal(0, 10), "b", dpar = muy2) +
#     prior(cauchy(0, 1), "Intercept") +
#     prior(normal(0, 2), "Intercept", dpar = muy3)
fit <- brm(bf(y | trials(size)  ~ 1, muy2 ~ x), data = dat, 
                family = multinomial())

dat
```


```{r}
# Ordinal regression modeling patient's rating of inhaler instructions
# category specific effects are estimated for variable 'treat'


#  Read CSV File
csv_file_clean <- read_csv("clean_data/nyc_names_vichy_complied.csv")
#  Read Shape File
shape_file_clean <- st_read("clean_data/nyc_data_vichy_complied.shp", crs = 4269)
#  Replace Column abbr Names in Shape File with full name from CSV
colnames(shape_file_clean) <- colnames(csv_file_clean)

# Verify
names(shape_file_clean)
names(csv_file_clean)
```


```{r eval=FALSE}
# fit2 <- brm(transportation_desert_4cat ~ 1 +  
#               mean_income + 
#               mean_rent + 
#               unemployment_count + 
#               school_count + 
#               store_count + 
#               bus_count + 
#               eviction_count + 
#               uninsured_count + 
#               white_count+ 
#               black_count+ 
#               latinx_count + 
#               asian_count + 
#               (1|borough) , 
#             data = csv_file_clean,
#             family= categorical(link = "logit"),
#             chains = 2,
#             iter = 2000)
# saveRDS(fit2, "trans_desert_multinomial_model.rds")
```


```{r eval=FALSE}
trans_desert_multinomial_model <- readRDS("trans_desert_multinomial_model.rds")
summary(trans_desert_multinomial_model)
plot(trans_desert_multinomial_model, ask = FALSE)
WAIC(trans_desert_multinomial_model)

pp_check(trans_desert_multinomial_model)
```



