---
title: "Shiny"
author: "Sam Ding"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(bayesrules)  # for the plotting functions
library(rstanarm)
library(dplyr)
```


```{r}
model <- readRDS("data/ordinal_model_2.rds") 
# modelNaive <- readRDS("naive_model_2.rds")
```

```{r}

# Build the server
server2 <- function(input, output) {
  
  

  

  output$resultTableOrdinal <- renderTable({
     # Prediciton from model
  pred <- posterior_predict(model,
                              newdata = data.frame(
    mean_income= input$mean_income,
    below_poverty_perc = input$below_poverty_perc,
    eviction_count = input$eviction_count,
    # school_count= input$school_count,
    store_count= input$store_count
    ))
  df <- as.data.frame(pred) %>%
    mutate(Classification  = case_when(
    `1` == 1 ~ 'Poor',
    `1` == 2 ~ 'Limited',
    `1` == 3 ~ 'Satisfactory',
    `1` == 4 ~ 'Excellent' )) %>%
  dplyr::select(Classification)
    
    tab <- table(df) %>% sort(decreasing=TRUE) %>% prop.table()
    names(dimnames(tab)) <- c("Transit_Accessibility")
    tab
    
  #   df <- as.data.frame(table(result)) %>% 
  # mutate(Prediction = Freq/sum(Freq)*100) %>%
  # mutate(Classification  = case_when(
  #   result == 1 ~ 'Poor', 
  #   result == 2 ~ 'Limited', 
  #   result == 3 ~ 'Satisfactory', 
  #   result == 4 ~ 'Excellent' )) %>% 
  # relocate(Classification, .after = Prediction) %>% 
  # dplyr::select(Classification,Prediction)
  })
  
  # output$resultTableNaive <- renderTable({
  #    # Prediciton from model
  # pred <- predict(naive_model_2, 
  #       newdata = data.frame( 
  #   mean_income= input$mean_income,
  #   below_poverty_perc = input$below_poverty_perc,
  #   evictions_perc = input$evictions_perc,
  #   school_count= input$school_count,
  #   store_count= input$store_count)
  #   , type = "raw")
  # pred
  #   
  #   # tab <- df %>% sort(decreasing=TRUE)
  #   # names(dimnames(tab)) <- c("Transit_Accessibility")
  #   # tab
  # })

}


# Build the user interface
ui2 <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      # h4("Demographic Information"), 
      # sliderInput("total_pop", "Total Population", min = 0, max = 100000, value = 10),
      sliderInput("mean_income", "Mean Income per Year (in USD)", min = 0, max = 300000, value = 10),
      # sliderInput("unemployment_perc", "% of Unemployment", min = 0, max = 100, value = 1),
      sliderInput("below_poverty_perc", "% Below Poverty", min = 0, max = 100, value = 1),
      sliderInput("eviction_count", "Number of Evictions", min = 0, max=1500, value =1),
      # h4("Population"), 
      # sliderInput("white_perc", "% of White", min = 0, max = 100, value = 1),
      # sliderInput("asian_perc", "% of Asian", min = 0, max = 100, value = 1),
      # sliderInput("black_perc", "% of Black", min = 0, max = 100, value = 1),
      # sliderInput("latinx_perc", "% of Latinx", min = 0, max = 100, value = 1),
      # h4("Store and School Count"), 
      sliderInput("store_count", "Store Count", min = 0, max = 250, value = 1),
      # sliderInput("school_count", "School Count", min = 0, max = 40, value = 1),
      
    ),
    mainPanel(
      # h4("Plot of the prior pdf:"), 
      # plotOutput("priorPdf"),
      h4("Model Predictions"), 
      tableOutput("resultTableOrdinal")
      # tableOutput("resultTableNaive")
    )
  )
)

# Run the shiny app!
shinyApp(ui = ui2, server = server2)
```

